---
- name: Install fish
  apt:
    name: fish

- name: Default shell
  user:
    name: vagrant
    shell: /usr/bin/fish

- name: Add alias for kubectl
  become: false
  lineinfile:
    path: .config/fish/config.fish
    line: alias k "kubectl"
    create: yes
